### PR TITLE
API rework phase 3 tests

### LINKED ISSUE #97: API tests
Phase 3

### LINKED ISSUE #98: check build
> Task :compileJava
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 17
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 13s
1 actionable task: 1 executed

### LINKED ISSUE #99: api tests failed
/home/runner/work/Java-discord/Java-discord/src/test/testUtils/SeekCommandTestMocker.java:11: error: package org.mockito does not exist
[25](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:26)
> Task :compileJava
[26](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:27)
import org.mockito.ArgumentCaptor;
[27](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:28)
                  ^
[28](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:29)
/home/runner/work/Java-discord/Java-discord/src/test/testUtils/SeekCommandTestMocker.java:13: error: package org.mockito does not exist
[29](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:30)
import static org.mockito.Mockito.*;
[30](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:31)
                         ^
[31](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:32)
/home/runner/work/Java-discord/Java-discord/src/test/testUtils/SeekCommandTestMocker.java:17: error: cannot find symbol
[32](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:33)
    public static CommandEvent createMockCommandEventWithTime(ArgumentCaptor<String> stringArgumentCaptor,
[33](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:34)
                                                              ^
[34](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:35)
  symbol:   class ArgumentCaptor
[35](https://github.com/Andreichenko/Java-discord/runs/6762786593?check_suite_focus=true#step:5:36)
  location: class SeekCommandTestMocker

### LINKED ISSUE #100: Api tests failed with error in line:13
/home/runner/work/Java-discord/Java-discord/src/test/testUtils/SeekCommandTestMocker.java:13: error: package org.mockito does not exist

### LINKED ISSUE #101: test module has some errors
output will be later

### PR DESCRIPTION
**Pull request by Andreichenko**
API testing with mock tests. This way we will check API compatibility after which we can start creating a server and testing the application in an isolated environment.

### CODE REVIEW

File: src/main/java/bot/commands/text/WhisperTextCommand.java [hunk 1]
```diff
@@ -16,7 +17,7 @@ public WhisperTextCommand() {
     }
 
     @Override
-    protected void execute(CommandEvent event) {
+    protected void execute(CommandEvent event, IMessage) {
```
Comment (Andreichenko) [inline src/main/java/bot/commands/text/WhisperTextCommand.java]: It is expected that there will be an error, as the argument doesnt exist

File: src/main/java/bot/commands/text/WhisperTextCommand.java [hunk 2]
```diff
@@ -3,6 +3,7 @@
 import bot.utils.commands.Command;
 import bot.utils.commands.CommandEvent;
 import net.dv8tion.jda.api.Permission;
+import org.aspectj.bridge.IMessage;
```
Comment (Andreichenko) [inline src/main/java/bot/commands/text/WhisperTextCommand.java]: check

**Review by Andreichenko — COMMENTED** [review]
check

File: src/main/java/bot/commands/text/WhisperTextCommand.java [hunk 3]
```diff
@@ -3,7 +3,6 @@
 import bot.utils.commands.Command;
 import bot.utils.commands.CommandEvent;
 import net.dv8tion.jda.api.Permission;
-import org.aspectj.bridge.IMessage;
```
Comment (Andreichenko) [inline src/main/java/bot/commands/text/WhisperTextCommand.java]: OK

File: src/main/java/bot/commands/text/WhisperTextCommand.java [hunk 4]
```diff
@@ -17,7 +16,7 @@ public WhisperTextCommand() {
     }
 
     @Override
-    protected void execute(CommandEvent event, IMessage) {
+    protected void execute(CommandEvent event) {
```
Comment (Andreichenko) [inline src/main/java/bot/commands/text/WhisperTextCommand.java:19]: OK

File: src/test/bot/commands/audio/SeekCommandTest.java [hunk 5]
```diff
@@ -18,12 +18,11 @@ public void init() {
         MockitoAnnotations.initMocks(this);
     }
 
-
+    @Test
```
Comment (Andreichenko) [inline src/test/bot/commands/audio/SeekCommandTest.java:21]: OK

File: src/test/testUtils/SeekCommandTestMocker.java [hunk 6]
```diff
@@ -81,6 +81,9 @@ public static CommandEvent createMockCommandEventThatFailsWithTime(ArgumentCapto
         when(mockAudioTrack.getDuration()).thenReturn(Long.valueOf(999999999));
         when(mockAudioTrack.isSeekable()).thenReturn(true);
 
+        AudioPlayer mockAudioPlayer = mock(AudioPlayer.class);
```
Comment (Andreichenko) [inline src/test/testUtils/SeekCommandTestMocker.java:84]: need to check

**Review by Andreichenko — COMMENTED** [review]
check

File: build.gradle [hunk 7]
```diff
@@ -72,4 +72,13 @@ test {
...
+}
+
+jar {
+    manifest {
+        attributes(
+                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
+                'Main-Class': mainClassName
+        )
+    }
 }
```
Comment (Andreichenko) [inline build.gradle:84]: nl

File: src/test/bot/commands/audio/SeekCommandTest.java [hunk 8]
```diff
@@ -76,7 +76,14 @@ public void seekWithInvalidFormatFails(){
     }
 
     public void seekWithStringFails(){
+        ArgumentCaptor<String> stringArgumentCaptor = ArgumentCaptor.forClass(String.class);
+
+        CommandEvent mockCommandEvent = SeekCommandTestMocker.createMockCommandEventThatFailsWithTime(stringArgumentCaptor,
+                "string");
```
Comment (Andreichenko) [inline src/test/bot/commands/audio/SeekCommandTest.java:82]: check "string"

File: src/test/bot/commands/audio/SeekCommandTest.java [hunk 9]
```diff
@@ -55,7 +55,7 @@ public void seekWithSeconds(){
         ArgumentCaptor<Long> longArgumentCaptor = ArgumentCaptor.forClass(Long.class);
 
         CommandEvent mockCommandEvent = SeekCommandTestMocker.createMockCommandEventWithTime(stringArgumentCaptor,
-                longArgumentCaptor, 0);
+                longArgumentCaptor, "2221");
```
Comment (Andreichenko) [inline src/test/bot/commands/audio/SeekCommandTest.java:58]: IT's OK

File: src/test/bot/commands/audio/SeekCommandTest.java [hunk 10]
```diff
@@ -65,26 +65,8 @@ public void seekWithSeconds(){
                 stringArgumentCaptor.getValue());
     }
 
-    @Test
```
Comment (Andreichenko) [inline src/test/bot/commands/audio/SeekCommandTest.java]: OK

File: src/test/bot/commands/audio/SeekCommandTest.java [hunk 11]
```diff
@@ -65,26 +65,8 @@ public void seekWithSeconds(){
...
-    public void seekWithInvalidFormatFails(){
-        ArgumentCaptor<String> stringArgumentCaptor = ArgumentCaptor.forClass(String.class);
-        CommandEvent mockCommandEvent = SeekCommandTestMocker.createMockCommandEventThatFailsWithTime(stringArgumentCaptor,
-                "3:4:5:6");
-        SeekCommand seekCommand = new SeekCommand();
-        seekCommand.execute(mockCommandEvent);
-        assertEquals(TextChannelResponses.SEEK_COMMAND_FORMAT, stringArgumentCaptor.getValue());
-    }
 
-    public void seekWithStringFails(){
```
Comment (Andreichenko) [inline src/test/bot/commands/audio/SeekCommandTest.java]: OK

**Comment by Andreichenko** [comment]
Okay we should move to the next step
